project:
  type: website
  output-dir: docs
  
website:
  title: "RuDiPro"
  navbar:
    left:
      - href: index.qmd
        text: главная
      - href: about.qmd
        text: о проекте
      - href: dialects.qmd
        text: информация о говорах
      - href: rhythm.qmd
        text: ритмическая структура
      - href: map.qmd
        text: карта
      - href: data.qmd
        text: данные
        
format:
  html:
    theme: cosmo
    csl: apa.csl
    toc: true
    embed-resources: true
    page-layout: full
    bibliography: bibliography.bib
