---
language: custom.yml
---

## Тверской (Говор 8) {#d8}

Говор дд. Скнятино, Волнога, Красная горка, Коротково и с. Капшино относится к Тверской подгруппе Владимирско-Поволжской группы восточных среднерусских окающих говоров и локализуется в восточной части территории, охватываемой этой подгруппой.

Говор характеризуется пятифонемным ударным вокализмом, неполным оканьем (впрочем, непоследовательным, при котором на месте /о/ в первом предударном слоге иногда произносится [а] или [ъ]) и различением [а] на месте /а/ и [е] на месте /е/, /о/ в первом предударном слоге после мягких согласных; образец говора и краткое описание см. в [@dyachyenko20].

Ритмическая структура слова характеризуется предельной степенью выраженности двухступенчатой редукции гласных. «Гласные значительно длиннее согласных своего слога, предударный гласный нередко равен, а часто и длиннее ударенного» [@visotskiy73: 35]. По классификации С.С. Высотского эти говоры относятся к IV типу и имеют следующее соотношение длительностей предударных и ударных гласных: 28 мс (гласный второго предударного слога) – 175 мс (гласный первого предударного слога) – 171 мс (гласный ударного слога) [@visotskiy73: 35-38].

Спецификой говора по сравнению с другими среднерусскими и литературным русским языком является фонетическая реализация мелодического контура общего вопроса, в частности, возможность сверхраннего тайминга восходящего тонального акцента. Эта особенность сближает его с архангельскими и западными среднерусскими говорами, от архангельских все среднерусские диалекты отличаются отсутствием сохранения высокого тона на заакцентных слогах. От восточного среднерусского окающего говора Владимирско-Поволжской группы он отличается также отсутствием отрицательного заноса (нисходящего движения тона на предударном слоге перед его повышением в начале ударного). Отличие от литературного русского языка состоит ещё и в отсутствии усечения тонального контура при его реализации на последнем слоге во фразе. От самого близкого в этом отношении соседнего селигеро-торжковского говора тверской отличается большей частотностью сверхраннего тайминга (тональный максимум восходящего акцента может достигаться в начале согласного инициали ударного слога) и отсутствием фразового тона. Таким образом, мелодический контур в целом имеет вид `%L (L+)H* (L-) L%`.

Подробнее смотрите [@dyachyenko20; @visotskiy73; @knyazev_unpubl_a].

## Селигеро-Торжсковский (Говор 4) {#d4}

Говор с. Ильинское относится к Селигеро-Торжковским западным среднерусским акающим говорам.

Говор характеризуется пятифонемным ударным вокализмом и недиссимилятивным аканьем, у части информантов отмечено еканье, у другой части – иканье. Селигеро-Торжсковские говоры весьма неоднородны, в частности, по характеру безударного вокализма, который может быть представлен различными типами яканья, еканьем или иканьем [@zakharova70: 414]. Встречаются и более сложно устроенные системы предударного вокализма. Так, говор д. Лужниково Вышневолоцкого района, расположенной западнее Ильинского, характеризуется переходным типом вокализма: у части информантов наблюдается различение, с одной стороны, фонемы /а/, с другой – фонем /е/ и /о/, у другой части информантов – ассимилятивно-диссимилятивное яканье култуковского типа, однако все информанты демонстрируют неустойчивость системы предударных гласных и большую вариативность гласных в первом предударном слоге [@malisheva20: 231-239].

С точки зрения ритмической структуры слова Селигеро-Торжковские говоры относятся к группе VII по классификации С.С. Высотского. Типологической особенностью этой группы является заметная двухступенчатость редукции безударных гласных, при которой, однако, хотя просодическое ядро существенно выделяется в отношении длительности гласных, гласные 2-го предударного слога не склонны к сильному сокращению (как, например, в говорах Владимирско-Поволжской группы), а соотношение длительностей гласных второго предударного – первого предударного и ударного слогов составляет 70 мс – 125 мс – 151 мс [@visotskiy73: 35-38].

Основным отличием фонетической реализации мелодического контура общего вопроса в западном среднерусском акающем Селигеро-Торжковском говоре по сравнению с другими среднерусскими говорами (и литературным русским языком) является отмечаемая в речи самых старших информантов возможность сверхраннего тайминга восходящего тонального акцента. Эта особенность сближает его с архангельскими говорами, от которых все среднерусские диалекты отличаются отсутствием сохранения высокого тона на заакцентных слогах. От восточного среднерусского окающего говора Владимирско-Поволжской группы он отличается также отсутствием отрицательного заноса (нисходящего движения тона на предударном слоге перед его повышением в начале ударного). Отличие от литературного русского языка состоит еще и в отсутствии усечения тонального контура при его реализации на последнем слоге во фразе.

В говоре происходит перестройка мелодического контура общего вопроса: тональный максимум восходящего акцента смещается от начала ударного гласного акцентоносителя к его середине (по всей видимости – под влиянием литературного языка, в котором восходящее движение характеризуется максимально поздним таймингом): `%L H* L- L%` --> `%L L+H* L- L%`.

Подробнее смотрите [@visotskiy73; @zakharova70; @knyazev23melodicheskiyI; @malisheva20].

## Псковский (Говор 1) {#d1}

Говор деревень Дарьино, Логовино и Котельно Островского района Псковской области относится к Псковской группе западных среднерусских говоров. В говоре пятифонемный ударный вокализм, недиссимилятивное аканье и сильное яканье.

Ритмика слова предполагает выраженную (хотя и не настолько, как, например, во Владимирско-Поволжских говорах) двухступенчатость редукции гласных первого и второго предударных слогов при среднем темпе речи. По классификации С.С. Высотского эти говоры относятся к X группе и имеют следующее соотношение длительностей предударных и ударных гласных: 78 мс (гласный второго предударного слога) – 96 мс (гласный первого предударного слога) – 120 мс (гласный ударного слога) [@visotskiy73: 36-38].

Основным отличием фонетической реализации мелодического контура общего вопроса в этом говоре по сравнению с другими среднерусскими говорами (и литературным русским языком) является возможность сверхраннего тайминга восходящего тонального акцента. Эта особенность сближает его с архангельскими говорами, от которых все среднерусские диалекты отличаются отсутствием сохранения высокого тона на заакцентных слогах. От восточного среднерусского окающего говора Владимирско-Поволжской группы он отличается также отсутствием отрицательного заноса (нисходящего движения тона на предударном слоге перед его повышением в начале ударного). Отличие от литературного русского языка состоит еще и в отсутствии усечения тонального контура при его реализации на последнем слоге во фразе. От самого близкого в этом отношении селигеро-торжковского говора псковский отличается большей частотностью сверхраннего тайминга (тональный максимум восходящего акцента может достигаться в начале согласного инициали ударного слога) и регулярным отсутствием фразового тона. Таким образом, мелодический контур в целом имеет вид `%L (L+)H* (L-) L%`.

Подробнее смотрите [@visotskiy73; @knyazev23melodicheskiyII].

## Роговатка (Говор 2) {#d2}

Говор с. Роговатое Старооскольского района Белгородской области принадлежит к Оскольским межзональным говорам типа Б южнорусского наречия.

Этот идиом достаточно хорошо изучен, его описанию посвящена обширная литература, существует звучащий корпус роговатовского говора.

В отношении системы гласных говор характеризуется архаическим диссимилятивным аканьем и архаическим диссимилятивным яканьем двух разновидностей: у одних информантов (как правило, самых старших) это классический задонский подтип, у других – «умеренный» задонский, при котором перед ударными гласными среднего и нижнего подъёмов предударные гласные, реализующие фонемы неверхнего подъёма, совпадают в и-образном звуке перед последующим мягким согласным и в е-образном звуке перед последующим твёрдым согласным.

В отношении ритмической структуры в говоре наблюдается два типа случаев: 1) с гласным [а] в первом предударном слоге и гласными верхнего и верхне-среднего подъёма под ударением, 2) с гласным не-а в первом предударном слоге и гласными среднего и нижнего подъёма под ударением. В первом случае отмечается заметная двухступенчатость редукции гласных первого и второго предударных слогов, «гласный второго предударного слога не склонен к сильному сокращению, но сохраняет тембр редуцированного» [@visotskiy73: 36-37]. Во втором случае двухступенчатость редукции также выражена, однако длительность первого предударного слога существенно меньше, чем в первом случае, она примерно соответствует длительности гласных верхнего подъёма в этой же позиции, однако превышает длительность редуцированных гласных во втором предударном слоге. Темп речи в таких говорах средний. По классификации С.С. Высотского подобные говоры относятся к XII и XIII группам и имеют, соответственно, следующее соотношение длительностей предударных и ударных гласных: 1) 58 мс (гласный второго предударного слога) – 113 мс (гласный первого предударного слога) – 123 мс (гласный ударного слога), 2) 43 мс (гласный второго предударного слога) – 70 мс (гласный первого предударного слога) – 120 мс (гласный ударного слога) [@visotskiy73: 38].

Основным отличием просодической системы южнорусского говора от литературной русской является ее ориентация на использование преимущественно ровных (уровневых) тонов, а не контурных (скользящих), составляющих ядро интонационной системы литературного языка. Просодическое оформление в говоре таких коммуникативных категорий, как утверждение, общий вопрос, вопрос с вопросительным словом, вокатив, императив и переспрос, может быть описано с ипользованием двух монотональных акцентов – `Н*` и `L*`. Кроме того, мы постулируем в говоре Роговатки два конечных пограничных тона (`H%` и `L%`), каждый из которых может сочетаться с любым из двух тональных акцентов. При этом фактов, позволяющих утверждать существование фонологического противопоставления разных фразовых тонов (`Н-` и `L-`), в ходе анализа не обнаружено. Одной из важнейщих особенностей фразовой просодии Роговатого является редкое в типологическом отношении противопоставление двух типов начальных пограничных тонов – `%Н` и `%L`.

Подробнее смотрите [@bukrinskaya14; @visotskiy73; @dyachyenko16; @dyachyenko21arkhaicheskoye; @dyachyenko13glasniye; @dyachyenko21glasniye; @dyachyenko15; @dyachyenko21instrumentalno_foneticheskoye; @dyachyenko14; @dyachyenko17osobennosti; @dyachyenko13ekspeditsiya; @dyachyenko19; @dyachyenko17obrazy; @dyachyenko18; @knyazev24frazovaya; @teravanesova15; @teravanesova11; @teravanesova21; @teravanesova18]

## Новгородский (Говор 6) {#d6}

Говор деревень Ильмень, Хотяж и Курицко Новгородского района Новгородской области относится к Новгородской группе западных среднерусских окающих говоров. Он характеризуется неполным оканьем, при котором в первом предударном слоге после твёрдых согласных фонемы /а/ и /о/ различаются, а в других безударных слогах совпадают, как правило, в звуке [ъ] (в конечном открытом слоге перед паузой – чаще в [а]). После мягких согласных в первом предударном слоге также наблюдается различение /а/, /о/, /е/ и /и/, однако /о/ и /е/ могут совпадать в е-образном звуке, в других безударных слогах /а/, /о/ и /е/ нейтрализуются в и-образном звуке (но в конечном открытом слоге /а/ обычно представлена а-образным звуком, а /о/ и /е/ – е-образным).

Специфика интонационного оформления фразы, а также место размещения тонального акцента (тайминг) связаны с устройством ритмической структуры слова. В отношении ритмической структуры новгородские говоры при среднем темпе речи характеризуются достаточно выраженной двухступенчатостью признаков безударности: первый предударный слог значительно более долгий, чем другие безударные, хотя этот контраст выражен гораздо меньше, чем во владимирских говорах и литературном русском языке [@visotskiy73: 35–36].

Просодическая система говора весьма сходна с литературной как в отношении набора фонологических тональных средств, так и в плане их использования для оформления базовых коммуникативных категорий – общего и частного вопроса, утверждения, незавершенности, императива. Как и в литературном языке, мы постулируем в ней три тональных акцента – восходящий, нисходящий и низкий, а также два базовых конечных пограничных тона – высокий и низкий. Фонологические различия между начальными пограничными тонами и фразовыми тонами, по-видимому, отсутствуют. При этом основные различия между говором и литературным языком заключаются в фонетической реализации тональных акцентов и их употреблении: 1) восходящий тональный акцент (`L+H*`) характеризуется более ранним таймингом достижения тонального максимума – в середине, а не в конце ударного слога; 2) наоборот, тайминг нисходящего тонального акцента (`H*+L`) является более поздним: начало падения тона приходится на середину, а не начало ударного гласного, причем понижению предшествует повышение на самóм ударном, а не на предударном гласном, что объясняется отличием ритмической структуры слова говора от литературной; 3) утвердительные предложения как с узким, так и с широким фокусом в говоре в подавляющем большинстве случаев оформляются при помощи нисходящего акцента `H*+L`; акцент `L*` используется преимущественно в составе мелодического контура с высоким конечным пограничным тоном.

Подробнее смотрите [@visotskiy73; @knyazev23melodicheskiy]

## Белозерско-Бежецкий (Говор 7) {#d7}

Говор деревень Ковжи, Куности, села Артюшина и города Белозерска принадлежит к Белозерско-Бежецким межзональным говорам севернорусского наречия, которые занимают промежуточное положение между Вологодской и Ладого-Тихвинской группами. Белозерско-Бежецкие говоры неоднородны: в соответствии с современным диалектным членением они образуют межзональную группу говоров северного наречия, в то время как в членении 1915 г. внутри этой группы проходила граница всего северновеликорусского наречия и среднерусских говоров (белозерские относились к северным, а бежецкие – к среднерусским). Это различие связано «с историей заселения края славянами, а именно с преобладанием в северной части края выходцев из Новгородской земли, а в южной – из Ростово-Суздальского княжества» [@beguntz06: 4].

Говор деревень рядом с Белозерском характеризуется пятифонемным ударным вокализмом, при котором, однако, на месте старого ѣ перед последующим мягким согласным встречается гласный [и] (а перед твёрдым – спорадически дифтонг [ие]), полным оканьем, различением гласных в первом предударном слоге после мягких согласных, однако непоследовательным, заударным ёканьем, более подробное описание говора, включающее характеристику системы согласных, а также грамматических и лексических черт говора, см. в [@bukrinskaya23: 280-282].

С точки зрения ритмической структуры слова рассматриваемому говору свойственна чрезвычайно слабо выраженная (хотя все же наличествующая) двухступенчатость редукции безударных гласных. Гласные ударного, первого и второго предударного слогов незначительно различаются по длительности, их соотношение следующее: 45 мс (второй предударный) – 50 мс (первый предударный) – 88 мс (ударный) [@visotskiy73: 36-38].

Основным отличием фонетической реализации мелодического контура общего вопроса в белозерском говоре по сравнению с севернорусскими архангельскими, среднерусскими и современным русским литературным языком является позднее (на гласном ударного слога) начало восходящего движения тона (‘low turning point’); от среднерусских говоров и литературного языка он – наряду с архангельскими – отличается также наличием ровного высокого тона на заакцентных слогах; общей с литературным русским языком особенностью белозерского говора является поздний тайминг восходящего акцента: высшая точка частоты основного тона  в нем достигается в самом конце ударного гласного, а при наличии последующего сонорного согласного – в его начале, вне зависимости от принадлежности этого сонорного к ударному или заударному слогу; как и во всех исследованных до сих пор диалектах (в отличие от литературного языка) усечение тонального контура при его реализации на последнем слоге во фразе отсутствует. Таким образом, тональный контур общего вопроса в белозерских говорах имеет структуру `%L L*+H Н- L%`; при этом есть основания полагать, что незавершенность в том же говоре оформляется иначе – контуром `%L L*+H L- L%`.

Подробнее смотрите [@beguntz06; @bukrinskaya23; @visotskiy73; @knyazev23tonalniy]

## Владимирский – ок и ак (Говор 91, 92) {#d9}

Материалом исследования окающего владимирского говора служили звуковые записи спонтанной речи жительниц д. Лазаревка и сел Заколпье, Крюково Гусь-Хрустального района, с. Синжаны и д. Тимошино Меленковского района Владимирской области.

Рассматриваемый говор характеризуется пятифонемным ударным вокализмом, чередованием ударных гласных [е]/[и] в зависимости от твердости/мягкости последующего согласного ([м’е́стъ], [л’ес], но [м’и́с’ьц], [д’и́н’г’и], [з’д’ис’]), неполным оканьем, при котором в первом предударном слоге после твердых согласных фонемы /а/ и /о/ различаются, а в других безударных слогах совпадают, как правило, в звуке [ъ] (который иногда, обычно во втором предударном прикрытом слоге, сокращается практически до нуля), но в конечном открытом слоге перед паузой – чаще в [а]: [воз’и́ла], [жона́], [дава́л], [ръспрос’и́л], [пм’ина́ла], [пло́ха]. В начальном неприкрытом втором предударном слоге /а/ и /о/ нейтрализуются в звуке [у]: [утр’еза́т’], [утказа́л]. После мягких согласных перед твердыми в первом предударном слоге наблюдается различение [а], [о], [е], а перед мягкими – различение [а] и [е], в других безударных слогах /а/, /о/ и /е/ нейтрализуются в и-образном звуке (но в конечном открытом слоге /а/ обычно представлена а-образным звуком, а /о/ и /е/ – е-образным): [с’емна́ццът’], [с’остра́], [к рыч’ага́м-тъ], [пръв’ер’а́й], [тр’ас’о́т], [п’ир’ейт’и́], [в’е́ч’иръм], [ду́с’а], [гр’и́н’к’е].

Информанты в большинстве демонстрируют хорошую степень сохранности говора, отступления от описанной выше системы единичны. Только одна из информанток, ЕАС1932, в этом отношении отличается от остальных: будучи достаточно хорошо образованным по деревенским меркам того времени человеком, она всю жизнь проработала на почте и была ориентирована на «городскую» речь, чему способствовало также то, что немало времени она проводила у двух своих дочерей, проживающих в городе. В частности, наряду с примерами различения гласных /о/ и /а/, в ее речи встречаются и случаи неразличения (аканья), то есть произношения [а] на месте /о/: [кота́], [згор’е́ла], [уход’и́ла] но [харо́шуйу], [ад’д’е́л ка́дръф], [кан’ч’а́ла], [ган’а́л’и]. Практически не встречается в речи ЕАС1932 примеров ёканья, то есть после мягких согласных в первом предударном слоге различаются только [е] и [а] (впрочем, тоже непоследовательно, зачастую совпадая в и-образном звуке), независимо от твёрдости/мягкости последующего согласного: [н’ич’ево́], [фс’ему́], [п’етро́в’ич’], [св’аш’ш’е́н’н’ик] и [св’иш’ш’е́н’н’ик], [д’ила́], [т’ижо́лый], [р’ип’е́й], [см’иjо́цца] и т.д. Тем не менее, в плане интонационного оформления речи идиолект ЕАС1932 почти не отличается от идиолектов остальных информантов.

Материалом исследования акающего владимирского говора служили звуковые записи спонтанной речи жителей деревень Труфаново, Мокрое, Тальново, Старково, Рязаново и Уляхино Гусь-Хрустального района Владимирской области.

Эти акающие говоры не вполне однородны как в отношении системы гласных, так и в отношении системы согласных. Ударный вокализм говора деревень Тальново и Старково семифонемный: фонемы верхне-среднего подъёма реализуются звуками [ê] и [ô], а фонемы среднего подъёма – звуками [е] и [о]. В говоре деревень Труфаново, Мокрое, Рязаново и Уляхино этого противопоставления не наблюдается, ударный вокализм пятифонемный. В области предударного вокализма говоры Тальнова, Старкова, Труфанова, Мокрого и Рязанова не различаются: всюду сильное аканье и непоследовательное еканье с вариативностью [е]/[и] в первом предударном слоге. В говоре д. Уляхино сильное аканье и яканье сложного устройства, которое в первом приближении может быть описано как умеренное: перед твёрдыми согласными гласные неверхнего подъёма совпадают в звуке [а], а перед мягкими – в звуке [е], более подробное описание вокализма этого говора см. в [@morakhovskaya57] и [@isaev04].

Различия наблюдаются также в том, как устроена система согласных. Говор Старкова и Тальнова характеризуется апикальной артикуляционной базой. Переднеязычные согласные перед гласными переднего ряда слабо палатализованные: [н·им·е́дл·инъ], [т·ирп·и́мъ], [д·е́нг·и], перед гласными непереднего ряда противопоставление мягких/немягких согласных выражается преимущественно посредством гласных: после «мягких» переднеязычных наблюдаются гласные, имеющие дифтонгический характер: [кат·ио́нка], [пар·иа́дък], после губных – «j+гласный»: [п·jат’], [вы́м·jа]. С этой «немягкостью» согласных, вероятно, связано то, что жителей Тальнова и Старкова, которые в былые времена ездили по России продавать ковры собственного изготовления, в других регионах называли «хохлами» (об этом рассказывает информантка ЕВС1940). В говоре деревень Труфаново, Мокрое, Рязаново и Уляхино переднеязычные согласные дорсальные. Говор деревни Уляхино, в отличие от всех остальных рассмотренных, характеризуется при этом твёрдым цоканьем.

Владимирские говоры относятся к Владимирско-Поволжской группе говоров, их яркой типологической особенностью является двухступенчатость редукции безударных гласных, которая «выражена с предельной силой, гласные длиннее согласных своего слога, предударный гласный нередко равен, а часто длиннее ударенного [@visotskiy73: 35]; соотношение длительностей гласных второго предударного – первого предударного и ударного слогов составляет 10% – 103% – 100% [@visotskiy73: 38]. Наоборот, севернорусские говоры представляют собой «резко противоположный предыдущим тип по реализации двухступенчатости. Последняя выражена очень слабо» [Там же: 36] (51% – 57% – 100% [@visotskiy73: 38]). В западных среднерусских говорах «двухступенчатость выражена несколько больше» [@visotskiy73: 36], нежели в северных (58% – 80% – 100% [@visotskiy73: 38]), но далеко не так ярко, как во владимирских. Соотношение длительности ударного и первого предударного слогов может влиять на выбор места размещения тонального акцента в слове: так, в московском варианте современного русского литературного языка (СРЛЯ) тональный максимум восходящего заноса в вопросах с вопросительным словом и утверждениях с узким фокусом (ИК-2) достигается существенно раньше, чем в вологодском варианте, где длительность первого предударного слога относительно ударного заметно меньше, чем в московском [@duryagin22].

В целом просодическая система рассматриваемых владимирских говоров близка литературной как в отношении наличия сходных тональных акцентов (`L*`, `H*+L`, `L*+H`), так и в плане интонационного оформления базовых коммуникативных категорий – утверждения, общего и частного вопроса, незавершенности, императива. Основные её отличия от литературной заключаются 1) в наличии специфического восходящего тонального акцента `L+H*`, используемого для оформления утвердительных и императивных высказываний; 2) в наличии, как минимум, в прошлом тонального акцента `Н*` (в акающих говорах); 3) реализации восходящих тональных акцентов с отрицательным заносом (понижением частоты основного тона на предударном гласном); 4) более раннем тайминге восходящего `L*+H` и нисходящего `H*+L` тональных акцентов; 5) регулярном использовании высокого начального пограничного тона; 6) широком распространении нисходящего конечного пограничного тона (`HL%`); 7) наличии следов «пословного» тонального оформления высказывания. При этом различия между акающим и окающим говорами минимальны и заключаются не в наборе тональных фонологических средств, а в характере фонетической реализации и степени выраженности фонологических контрастов, а также в степени распространенности тех или иных просодических явлений.

Подробнее смотрите [@visotskiy73; @isaev04; @morakhovskaya57; @duryagin22; @knyazev23frazovaya]

## Церковное (Говор 52) {#d52}

Говор относится к юго-западной диалектной зоне Архангельских говоров [@getsova97]. Его описание см. в [@tserkovnoye]. 

Говор характеризуется наличием «пословного» мелодического контура с преобладанием нисходящих тональных акцентов и использованием высокого (фонетически среднего) пограничного тона для оформления незавершеннности [@knyazev21], нестандартным типом просодического членения высказывания [@knyazev23severnorusskaya].

Подробнее смотрите [@getsova97; @tserkovnoye; @knyazev21; @knyazev23severnorusskaya]

См. [Ритмическую структуру](rhythm.html#d52).

## Климовское (Говор 3) {#d3}

К числу наиболее ярких особенностей фразовой просодии в говоре села Климовского Коношского района Архангельской области относятся:

1) оформление общего вопроса тональным контуром с восходящим тональным акцентом и низким пограничным тоном без фразового тона `(L+H* L%)`, что отличает его как от северо-восточных архангельских, которым свойственен высокий фразовый тон `(L+H* Н- L%)`, так и от литературного русского языка (низкий фразовый тон, `L+H* L- L%`);
2) высокий начальный пограничный тон (`%Н`) в утвердительных предложениях;
3) ровный высокий тон (`Н*`) предъядерных тональных акцентов;
4) наличие даунстепа – понижения тонального уровня на каждом последующем
предъядерном тональном акценте (`!Н*`);
5) оформление незавершенности высказывания при помощи высокого конечного
пограничного тона (`Н%`), который также может быть реализован с даунстепом (`!Н%`).

Подробнее смотрите [@knyazev23intonatsiya]

## Смоленский (Говор 10) {#d10}

Просодическая система смоленского говора очень близка зафиксированной в говоре с. Роговатое Старооскольского района Белгородской области (говор 2).

Основным ее отличием от литературной русской является ориентация на использование преимущественно ровных (уровневых) тонов, а не контурных (скользящих). Просодическое оформление в говоре таких коммуникативных категорий, как утверждение, общий вопрос, вопрос с вопросительным словом, вокатив, императив и переспрос, может быть описано с ипользованием 

1) двух монотональных акцентов (`Н*` и `L*`), 
2) двух  начальных пограничных тонов (`%Н` и `%L`) и 
3) двух конечных пограничных тонов (`H%` и `L%`).

## Нехочи (Говор 11) {#d11}

Образцы из д. Нехочи отобраны из корпуса этого говора [@nekhochi]. Там же см. подробнее о говоре.

Ярчайшей особенностью фразовой просодии этого идиома является тональный акцент с низким ровным тоном в начале ударного слога акцентоносителя, последующим быстрым повышением до высокого и ровным высоким в конце ударного гласного и/или на первом заударном (после этого тональная цель может быть как низкой, так и высокой в зависимости от типа конечного пограничного тона).  Мы предварительно анализируем этот тональный акцент как `L*+H*` (`L*H*`).

## Архангельские говоры к северо-востоку от Северной Двины (Говоры 5, 51, 52, 53, 532, 54, 55, 56) {#d5}

Образцы из «северо-восточных» архангельских говоров (Вадюга, Кеба, Мосеево, Веегора, Нюхча, Ваймуша) отобраны из соответствующих диалектных корпусов:

- Корпус говоров бассейна Верхней Пинеги и Выи [@upperpinega]
- Корпус говора села Кеба [@keba]
- Корпус говора Средней Пёзы [@middlepyoza]
- Корпус говора деревни Веегора [@veegora]
- Корпус говоров Средней Пинеги [@middlepinega]

Там же см. подробнее об этих говорах.

Спецификой фразовой просодии этих идиомов является 
    1) оформление общего вопроса восходящим тональным акцентом с задержкой падения тона до конечного во фразе слога – высоким фразовым тоном (`L*+H H- L%` или `L+H* H- L%`) [@post08; @knyazev22o_strukture];
    2) оформление специального вопроса высоким тональным акцентом `Н*` [@knyazev22o_strukture];
    3) оформление утвердительных ответных диалогических реплик мелодическим контуром с низким тональным акцентом, высоким фразовым тоном и низким конечным пограничным `L* H- L%` [@knyazev23frazoviy];
    4) особый тип просодического членения высказывания [@knyazev23frazoviy].

К этим говорам во многом примыкают и идиомы дд. Сельцо и Тимошино (см. Корпус говоров среднего течения Северной Двины [@dvina])

Подробнее смотрите [@knyazev22o_strukture; @knyazev22o_frazovoy; @knyazev23severnorusskaya; @knyazev23frazoviy; @post08].

## Тамбовский (Говор 13) {#d13}

Просодическая система говора села Верхнеспасского очень близка владимирской (говоры 91, 92) как в отношении набора тональных акцентов (`L*`, `H*+L`, `L*+H`, `L+H*`) и пограничных тонов (`%H`, `%L`, `H%`, `L%`), так и в плане интонационного оформления базовых коммуникативных категорий – утверждения, общего и частного вопроса, незавершенности, императива.

Она характеризуется 

1) наличием специфического восходяще-нисходящего тонального акцента `L+H*`, используемого для оформления утвердительных и императивных высказываний; 
2) ранним таймингом восходящего `L*+H` и нисходящего `H*+L` тональных акцентов; 
3) регулярным использованием высокого начального пограничного тона и акцента L* в мелодическом контуре нейтрального утверждения. 

От владимирских говоров тамбовский отличается отсутствием

1) реализации восходящих тональных акцентов с отрицательным заносом (значимым понижением частоты основного тона на предударном гласном);
2) нисходящего конечного пограничного тона (`HL%`).

См. [Ритмическую структуру](rhythm.html#d13).

## Елецкий (Липецкий) (Говор 14) {#d14}

Говор сёл Свишни и Тростное Липецкой области относится к Елецким межзональным говорам группы Б южнорусского наречия.

Записи сделаны в 1991 г. С. В. Князевым и Е. В. Щигель.

Вокалической системе говора свойственно так называемое «протодиссимилятивное» аканье: гласный первого предударного слога после твердых согласных тем дольше ([ъ] < [ъ^а^] < [а^ъ^] < [а]), чем короче гласный ударного слога ([а] > [е], [о] > [ê], [ô] > [и], [ы], [у]) [@knyazev07]. После мягких согласных наблюдается несколько более сложная картина, связанная с влиянием на качество предударного гласного твердости/мягкости последующего согласного: перед гласными верхнего подъема произносится преимущественно [а], верхне-среднего – [е], среднего – [и], нижнего – [ь] (см. табл. @tbl-yelets).

| 1 предударный     | ударный | ударный | ударный |
|-------------------|---------|---------|---------|
|         а^65^   е^35^ | и       |    ы    |       у |
|   а^5^    е^81^   и^14^ |    ế    |         |    ố    |
|    е^16^   и^42^  ь^42^ |       е |         | о       |
| е^27^     и^21^   ь^52^ |         |    а    |         |

: Вокализм 1 предударного слога после мягких согласных в елецком говоре (верхний индекс обозначает количество соответствующих примеров в процентах от общего числа примеров в данной позиции) {#tbl-yelets}

Фразовая просодия говора представляет собой переходную ступень между 

1) ориентированной на (высокий `H*` и низкий `L*`) уровневые тоны интонационной системой Оскольского говора с. Роговатого [Князев 2024] и 
2) системой с преимущественно контурными тонами (восходящий `L*+H`, нисходящий `H*+L`, восходяще-нисходящий `L+H*`) владимирских [@knyazev23frazovaya] и тамбовских [Князев, Дьяченко 2024]. 

Набор тональных средств елецкого говора включает в себя
    
1) высокий (`%H`) и низкий (`%L`) начальные пограничные тоны; 
2) высокий (`H%`) и низкий (`L%`) конечные пограничные тоны; 
3) три тональных акцента:
    низкий `L*` (нейтральное утверждение),
    (восходящий +) высокий `(L+)H*` (общий вопрос, незавершенность),
    высокий (+ нисходящий) `H*(+L)` (узкий фокус, специальный вопрос, императив).

При этом два последних акцента соответствуют, по всей вероятности, исходному `H*`.

Фонологически мы интерпретируем их как `(L+)H*` и `H*(+L)` на том основании, что именно ровный высокий тон приходится в них на всю (обычно после глухих согласных) или основную часть ударного гласного слова-акцентоносителя (в среднем – 2/3 его общей длительности).

[@knyazev24frazovaya; @knyazev_unpubl_b; @knyazev07; @knyazev24yuzhnorusskaya]

### Образец

О-о, что делали! Бывало, вот тут два дедушки были добрые. Вот, значить, мы начинаем. Начинается махорка, сажать. Ну, махорка, так она и называлась, махорка – мы-то звали табак, но это махорка. Вот, значить, женщины сажають, а мы им воду носим. Вот эти два дедушки добрых – они нам хоть из бочки вынають вёдры и это, наливають нам. 

Вот это-т, махорку посодють, посодють, ну, посадили. А нас ни свет ни заря утром будють ей поливать, чтоб она не засохла - ну, ить мы нескольки там дней ходим ей поливать, потом отработались, всё. Мокрые, грязные, и руки-то уж у нас надсажёные: ну, вядр… вёдра потаскайся, а ведь ума-то не было: мы, значить, один перед одним, чтоб моя пара вперёд шла – видишь, как хочется-то. 

Теперь, значить, после этого закончили махорку, начинается прополка. Нас тоже: «Идите, полите!», да. Ну, сперва одних девчонок нас отбивали. Не больнё так прополем-то. Потом и с женщинами стали полоть ходить. Бывало, женщины-то вот, они кажется постарше нас, а ведь они покрепче нас, вот они-то грядки дойдуть, а мы: то гляди лопнет у нас поясница, да брюшина у нас почему-то болела, она щас-то не так-то болить. Ну почему она и изработанная, а ить не так болить. «Ох, – думаем, – грядку не дойдём, посваляемси». Ну, отдохнём, отдохнём – опять надо... 

Потом начинается просу полоть. Вот просу сеяли, на пшено-то какая идёть. Вот тут это опять наша работа, а потом начинають, кого куда. Вот у нас тут ясли были, кого в ясли швырнуть, чтобы с этими, с ребятишкими сидели играли, а женщины чтоб больше работали. Так и нас. Ну, а потом уж стали мы по пятнадцать лет, уж тогда мы стали самостоятельно работать, а как же. 

Ой, один раз пошли вот сюда, тут вот щас дома, а тут была чистая поле. Ну, утром рано вязать рожь пошли. А там в кустах, ещё и там лес, за этим, он и был там, лес. Как заворошилось чтой-то! Эх, как мы хватили, да назад! Что из нас ещё толку-то не было, господи, ну что там, пятнадцать лет! Ну, работали. 

Ну, а в войну, в войну всю времю на лошадях работали, на лошадях. Вожжи из рук ни выходили: пахать надо, дробачить надо, сеять надо. Посеяли там, туда-сюда – уже рабочая пора: копны возить надо, и снова надо пахать, снова рожь, надо ведь зерновые сеять. Вот так наша жизнь проходила кой-как…

## Рязанский (Говор 15) {#d15}

Говор сёла *Новоспасское* и деревень *Печерники*, *Хавертово* Рязанской области относится к Рязанской группе южнорусского наречия.

Записи сделаны в 1992 г. С.В.Князевым, А.Н.Левиной и Е.В.Щигель.

Фразовая просодия говора представляет собой следующую (по сравнению с [Елецким](dialects.html#d14)) ступень перехода от ориентированной на уровневые тоны интонационной системой Оскольского говора с. [Роговатого](dialects.html#d2) [@knyazev23frazovaya] к системе с преимущественно контурными тонами (восходящий `L*+H`, нисходящий `H*+L`, восходяще-нисходящий `L+H*`) владимирских [@knyazev_unpubl_b] и тамбовских [@knyazev24yuzhnorusskaya].

Набор тональных средств рязанского говора включает в себя

1. высокий (`%H`) и низкий (`%L`) начальные пограничные тоны; 
2. высокий (`H%`), низкий (`L%`) и нисходящий (`HL%`) конечные пограничные тоны; 
3. три тональных акцента:

    - «низкий» `L*` с высоким начальным пограничным тоном (`%Н`) – нейтральное утверждение,
    - «восходящий» (общий вопрос, незавершенность), фонетически реализуемый как 
        - `L*+H*` (низкий + восходящий + высокий, чаще всего), 
        - `(L+)H*` (восходящий + высокий, реже), 
        - `Н*` (ровный высокий, реже всего),
    - «нисходящий» (узкий фокус, специальный вопрос, императив), фонетически реализуемый как
        - `H*(+L)` (высокий + нисходящий, чаще всего), 
        - `H*` (ровный высокий, очень редко), 
        - `Н*+L` (нисходящий, очень редко)
        - `Н*+L*` (высокий + нисходящий + низкий, очень редко).

При этом два последних акцента соответствуют, по всей вероятности, исходному `H*`.

Фонологически мы интерпретируем их как `L*+H*` и `H*(+L)` на основании частоты встречаемости.